### ISSUE TITLE
Compilation of documentation related tasks

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk#226]
- [x] Update readthedoc links in readme (#202)

### Getting Started
- [x] Add screenshots of the kiosk and menu sequence
- [x] Update kiosk startup instructions to reflect the new menu
- [x] Can we provide guidance on which architecture of Linux window users need to install? https://github.com/vanvalenlab/kiosk/blob/mrgn-docs/docs/source/GETTING_STARTED.rst#local-docker-installation---windows

### Advanced Documentation
- [x] Write a description of each parameter selected during kiosk setup. (#201)

### Software Infrastructure
- [x] Kiosk inventory and description of how parts fit together (#203)
- [x] Add kiosk figure to docs
- [x] Add description of how data flows through the kiosk to facilitate understanding for the user
- [x] How does autoscaling work? What parameters are critical?

### Frontend
- [x] Description of input data requirements for running data through the frontend (#220)
- [x] Rewrite kiosk-frontend to reflect actual design and function of the current version of the frontend 

### Custom Consumer Jobs
- [x] Write an explanation for why a user would want to make a custom consumer
- [x] Add relevant content from redis-consumer Readme to the custom job tutorial page
- [x] Explain how to setup a new helmfile
- [x] Expand and provide examples of how to modify helmfiles to support autoscaling of a custom consumer
- [x] Update how the frontend needs to be modified to work with a new consumer

**Comment by willgraf** [comment]
Closed by #265
